/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulatedv7;

import java.io.*; 
import javax.swing.JOptionPane;
import java.io.File;
import javax.swing.*;
import java.util.Scanner;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Tela extends javax.swing.JFrame {

boolean ok;
//variável que ativará o botão com a quantidade de máquinas e tarefas
boolean confirmado=false;
// Variáveis necessrária para o Annealig
int maq, tar;
int tempos[][], setup[][];

Annealing an = new Annealing();
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tempoMelhor = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        melhorSol = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tempoAleatoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        solAleatoria = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        botaoIniciar = new javax.swing.JButton();
        escolherArquivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        maquinas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tarefas = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        sobreMenu = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulated Annealing by Vitor");
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Melhor solução"));

        jLabel4.setText("Sequência: ");

        jLabel5.setText("Tempo:");

        tempoMelhor.setEditable(false);
        tempoMelhor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempoMelhorActionPerformed(evt);
            }
        });

        melhorSol.setEditable(false);
        melhorSol.setOpaque(false);
        melhorSol.setPreferredSize(new java.awt.Dimension(3, 20));
        jScrollPane3.setViewportView(melhorSol);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempoMelhor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempoMelhor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Solução aleatória"));

        jLabel6.setText("Sequência: ");

        tempoAleatoria.setEditable(false);
        tempoAleatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempoAleatoriaActionPerformed(evt);
            }
        });

        jLabel7.setText("Tempo:");

        solAleatoria.setEditable(false);
        solAleatoria.setMinimumSize(new java.awt.Dimension(8, 20));
        solAleatoria.setOpaque(false);
        solAleatoria.setPreferredSize(new java.awt.Dimension(5, 20));
        jScrollPane2.setViewportView(solAleatoria);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempoAleatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempoAleatoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(5, 5, 5))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tempos"));

        botaoIniciar.setText("Iniciar");
        botaoIniciar.setEnabled(false);
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });

        escolherArquivo.setText("Escolher arquivo");
        escolherArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolherArquivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Máquinas: ");

        maquinas.setEditable(false);
        maquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maquinasActionPerformed(evt);
            }
        });

        jLabel2.setText("Tarefas:");

        tarefas.setEditable(false);
        tarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarefasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(escolherArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(botaoIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(maquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escolherArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sobreMenu.setText("Sobre");
        sobreMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sobreMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(sobreMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getAccessibleContext().setAccessibleName("Simulated Annealing aplicado ao PMPNRTSDS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        //Vetor da solução analisada
        int v[][] = new int[maq][tar];
        //Vetor que guarda a melhor solução
        int b[][] = new int[maq][tar];
        //Vetor da solução temporaria
        int t[][] = new int[maq][tar];
        an.geraAleatorio(v, b, maq, tar);
        
        //Colocando a solução na tela para exibir ao usuário
            String s = new String();
            s="";
            for(int li=0; li<maq; li++){
                    for(int ci=0; ci<tar; ci++){
                      if(v[li][ci]!=0)  s+=(" "+v[li][ci]); } 
            if(li<maq)s+="\n";}
            solAleatoria.setText(s);
        /*exibindo a solucao aleatoria
        String sol = new String();
        for(int i=0; i<tar; i++){
            sol+=v[i]+" ";
        }
        solAleatoria.setText(sol);*/
        tempoAleatoria.setText(""+an.tempMax(v, maq, tar, tempos, setup));
        
        an.annealing(v, t, b, maq, tar, tempos, setup);
        //Exibir a melhor sol
            s="";
            for(int li=0; li<maq; li++){
                    for(int ci=0; ci<tar; ci++){
                      if(b[li][ci]!=0)  s+=(" "+b[li][ci]); } 
            if(li<maq)s+="\n";}
            melhorSol.setText(s);
        
        tempoMelhor.setText(""+an.tempMax(b, maq, tar, tempos, setup));
        
    }//GEN-LAST:event_botaoIniciarActionPerformed

    private void tempoAleatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempoAleatoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempoAleatoriaActionPerformed

    private void maquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maquinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maquinasActionPerformed

    private void sobreMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreMenuMouseClicked
        JOptionPane.showMessageDialog(null,  "Simulated Annealing aplicado ao Problema de tempo de preparação sequenciamento em máquinas paralelas não-relacionadas\nCriado por Vitor \n2017-2018", "Sobre",3);
    }//GEN-LAST:event_sobreMenuMouseClicked

    private void tempoMelhorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempoMelhorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempoMelhorActionPerformed

    private void escolherArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolherArquivoActionPerformed
        FileNameExtensionFilter a = new FileNameExtensionFilter("Arquivos texto", "txt");
        JFileChooser v = new JFileChooser("C:\\Users\\vitor\\Desktop\\Projeto");
        v.setFileFilter(a);
        
        Scanner input = null;
        v.showOpenDialog(this);
        File ar = v.getSelectedFile();
        String nome = ar.getPath();
        System.out.println("Nome do arquivo: " + nome);
        
        try{
	input = new Scanner(new File(nome));}
        catch(FileNotFoundException fi){
			System.out.println("Erro ao abrir arquivo!");
                        JOptionPane.showMessageDialog(null, "Erro ao abrir arquivo!");
                        fi.printStackTrace(); }
        
        maq = Integer.parseInt(input.next());
        System.out.println("Maquinas " + maq);
        tar = Integer.parseInt(input.next());
        System.out.println("Tarefas: " + tar);
        
        maquinas.setText(""+maq);
        tarefas.setText(""+tar);
        
        int m=0;
        try{
                tempos = new int[maq][tar];
		int i=0;
		while(input.hasNextInt()){
			int x = input.nextInt();
			tempos[m][i]=x;
                        if(x==0){
                        JOptionPane.showMessageDialog(null, "Tempos de processamento incorretos!. Favor rever o arquivo de origem.", "Falha", 1);
                        botaoIniciar.setEnabled(false);
                        ok=false;
                        break;
                        }
                        //System.out.println("TEMPO " + m + i + " : "+ tempos[m][i]);
                        ++i;
                if(i==tar){ 
                    i=0; 
                    m++;
                }
                if(m==maq)break;
                }
               
		JOptionPane.showMessageDialog(null, "Tempos de processamento importados.", "Sucesso", 1);
                ok=true;}
                catch (Exception e){
		e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Tempos de processamento incorretos!. Favor rever o arquivo de origem.", "Falha", 1);
                }
        
		
                
                setup = new int[maq*tar][tar];
                m=0;
                while(m<maq){
		int i=0, j=0;
                
		while(input.hasNext()){
			int x = input.nextInt();
                        if(j==tar){
                                j=0;
                                i++;}
                        if(i>=tar)break;
                        //System.out.print("\nAT"+ m + " "+ i + " "+ j + ": ");
			setup[(m*tar) +i][j]=x;
                        //System.out.print(" "+ setup[(m*tar) +i][j]+ "\n");
			++j;
                }
                m++;
                }
                JOptionPane.showMessageDialog(null, "Tempos de setup importados.", "Sucesso", 1);
                
                confirmaValores();
                contaLinhas();
                
                if(ok)botaoIniciar.setEnabled(true);
    }//GEN-LAST:event_escolherArquivoActionPerformed

    public void confirmaValores(){
        int m=0;
        
        System.out.print("=TEMPOS=");
                for(m=0; m<maq; m++){
                    System.out.println("\nMaquina " + (m+1) + " :");
                for(int hi=0; hi<tar; hi++) System.out.print(tempos[m][hi]+" ");
                }
            m=0;
                do{
		System.out.println("\nSetups da maquina " + (m+1) + ": ");
                for(int l=0; l<tar; l++){ 
                    for(int c=0; c<tar; c++){
                        System.out.print(" "+setup[(m*tar) +l][c]);}
                    System.out.println("");
                }
                m++;}while(m<maq); 
        
    }
    
    public void contaLinhas(){
        int m=0;
                while(m<(maq*tar)){
                    if(setup[m].length !=tar){
                        ok=false;
                        JOptionPane.showMessageDialog(null, "Tempos de preparação incorretos!. Favor rever o arquivo de origem.", "Falha", 1);
                    }
                    m++;
                }
               
          m=0;
                while(m<maq){
                    if(tempos[m].length !=tar){
                        JOptionPane.showMessageDialog(null, "Tempos de processamento incorretos!. Favor rever o arquivo de origem.", "Falha", 1);
                        ok=false;
                    }
                    m++;
                }      
        
    }
    private void tarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarefasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarefasActionPerformed
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JButton escolherArquivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField maquinas;
    private javax.swing.JTextPane melhorSol;
    private javax.swing.JMenu sobreMenu;
    private javax.swing.JTextPane solAleatoria;
    private javax.swing.JTextField tarefas;
    private javax.swing.JTextField tempoAleatoria;
    private javax.swing.JTextField tempoMelhor;
    // End of variables declaration//GEN-END:variables
}
